#ifndef ISRH
#define ISRH

extern "C" {void isr00(void);}
extern "C" {void isr01(void);}
extern "C" {void isr02(void);}
extern "C" {void isr03(void);}
extern "C" {void isr04(void);}
extern "C" {void isr05(void);}
extern "C" {void isr06(void);}
extern "C" {void isr07(void);}
extern "C" {void isr08(void);}
extern "C" {void isr09(void);}
extern "C" {void isr0a(void);}
extern "C" {void isr0b(void);}
extern "C" {void isr0c(void);}
extern "C" {void isr0d(void);}
extern "C" {void isr0e(void);}
extern "C" {void isr0f(void);}
extern "C" {void isr10(void);}
extern "C" {void isr11(void);}
extern "C" {void isr12(void);}
extern "C" {void isr13(void);}
extern "C" {void isr14(void);}
extern "C" {void isr15(void);}
extern "C" {void isr16(void);}
extern "C" {void isr17(void);}
extern "C" {void isr18(void);}
extern "C" {void isr19(void);}
extern "C" {void isr1a(void);}
extern "C" {void isr1b(void);}
extern "C" {void isr1c(void);}
extern "C" {void isr1d(void);}
extern "C" {void isr1e(void);}
extern "C" {void isr1f(void);}
extern "C" {void isr20(void);}
extern "C" {void isr21(void);}
extern "C" {void isr22(void);}
extern "C" {void isr23(void);}
extern "C" {void isr24(void);}
extern "C" {void isr25(void);}
extern "C" {void isr26(void);}
extern "C" {void isr27(void);}
extern "C" {void isr28(void);}
extern "C" {void isr29(void);}
extern "C" {void isr2a(void);}
extern "C" {void isr2b(void);}
extern "C" {void isr2c(void);}
extern "C" {void isr2d(void);}
extern "C" {void isr2e(void);}
extern "C" {void isr2f(void);}
extern "C" {void isr30(void);}
extern "C" {void isr31(void);}
extern "C" {void isr32(void);}
extern "C" {void isr33(void);}
extern "C" {void isr34(void);}
extern "C" {void isr35(void);}
extern "C" {void isr36(void);}
extern "C" {void isr37(void);}
extern "C" {void isr38(void);}
extern "C" {void isr39(void);}
extern "C" {void isr3a(void);}
extern "C" {void isr3b(void);}
extern "C" {void isr3c(void);}
extern "C" {void isr3d(void);}
extern "C" {void isr3e(void);}
extern "C" {void isr3f(void);}
extern "C" {void isr40(void);}
extern "C" {void isr41(void);}
extern "C" {void isr42(void);}
extern "C" {void isr43(void);}
extern "C" {void isr44(void);}
extern "C" {void isr45(void);}
extern "C" {void isr46(void);}
extern "C" {void isr47(void);}
extern "C" {void isr48(void);}
extern "C" {void isr49(void);}
extern "C" {void isr4a(void);}
extern "C" {void isr4b(void);}
extern "C" {void isr4c(void);}
extern "C" {void isr4d(void);}
extern "C" {void isr4e(void);}
extern "C" {void isr4f(void);}
extern "C" {void isr50(void);}
extern "C" {void isr51(void);}
extern "C" {void isr52(void);}
extern "C" {void isr53(void);}
extern "C" {void isr54(void);}
extern "C" {void isr55(void);}
extern "C" {void isr56(void);}
extern "C" {void isr57(void);}
extern "C" {void isr58(void);}
extern "C" {void isr59(void);}
extern "C" {void isr5a(void);}
extern "C" {void isr5b(void);}
extern "C" {void isr5c(void);}
extern "C" {void isr5d(void);}
extern "C" {void isr5e(void);}
extern "C" {void isr5f(void);}
extern "C" {void isr60(void);}
extern "C" {void isr61(void);}
extern "C" {void isr62(void);}
extern "C" {void isr63(void);}
extern "C" {void isr64(void);}
extern "C" {void isr65(void);}
extern "C" {void isr66(void);}
extern "C" {void isr67(void);}
extern "C" {void isr68(void);}
extern "C" {void isr69(void);}
extern "C" {void isr6a(void);}
extern "C" {void isr6b(void);}
extern "C" {void isr6c(void);}
extern "C" {void isr6d(void);}
extern "C" {void isr6e(void);}
extern "C" {void isr6f(void);}
extern "C" {void isr70(void);}
extern "C" {void isr71(void);}
extern "C" {void isr72(void);}
extern "C" {void isr73(void);}
extern "C" {void isr74(void);}
extern "C" {void isr75(void);}
extern "C" {void isr76(void);}
extern "C" {void isr77(void);}
extern "C" {void isr78(void);}
extern "C" {void isr79(void);}
extern "C" {void isr7a(void);}
extern "C" {void isr7b(void);}
extern "C" {void isr7c(void);}
extern "C" {void isr7d(void);}
extern "C" {void isr7e(void);}
extern "C" {void isr7f(void);}
extern "C" {void isr80(void);}
extern "C" {void isr81(void);}
extern "C" {void isr82(void);}
extern "C" {void isr83(void);}
extern "C" {void isr84(void);}
extern "C" {void isr85(void);}
extern "C" {void isr86(void);}
extern "C" {void isr87(void);}
extern "C" {void isr88(void);}
extern "C" {void isr89(void);}
extern "C" {void isr8a(void);}
extern "C" {void isr8b(void);}
extern "C" {void isr8c(void);}
extern "C" {void isr8d(void);}
extern "C" {void isr8e(void);}
extern "C" {void isr8f(void);}
extern "C" {void isr90(void);}
extern "C" {void isr91(void);}
extern "C" {void isr92(void);}
extern "C" {void isr93(void);}
extern "C" {void isr94(void);}
extern "C" {void isr95(void);}
extern "C" {void isr96(void);}
extern "C" {void isr97(void);}
extern "C" {void isr98(void);}
extern "C" {void isr99(void);}
extern "C" {void isr9a(void);}
extern "C" {void isr9b(void);}
extern "C" {void isr9c(void);}
extern "C" {void isr9d(void);}
extern "C" {void isr9e(void);}
extern "C" {void isr9f(void);}

#endif
